<?php
/**
 * auto generated by tinyorm 2016-02-20 16:22:02
 * @property int $id
 * @property string $c_varchar
 * @property int $c_int
 * @property string $c_unique
 */

namespace tinyorm\test;
/**
 * Class TestEntity
 * @package tinyorm\test
 *
 * @method static TestEntity find(int $id)
 */
class TestEntity extends \tinyorm\Entity {
    protected $dbName = 'test';
    static protected $sourceName = 'test';
    protected $pkName = 'id';
    protected $autoUpdatedCols = array ();
    function getDefaults() {
        return [
            'id' => NULL,
            'c_varchar' => NULL,
            'c_int' => NULL,
            'c_unique' => NULL,
        ];
    }
}
